# Generated by Django 4.1.5 on 2024-06-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_candidate_votes_recieved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="House",
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
