# Generated by Django 4.1.5 on 2024-06-11 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_position_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="candidate",
            name="House",
            field=models.CharField(default=None, max_length=254),
        ),
    ]
