# Generated by Django 4.1.5 on 2024-06-12 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_candidate_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="candidate",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.position"
            ),
        ),
    ]
