# Generated by Django 4.1.5 on 2024-06-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_candidate_position"),
    ]

    operations = [
        migrations.DeleteModel(name="Teachers",),
    ]
