# Generated by Django 4.1.5 on 2024-06-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_visited_check"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="House",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
