# Generated by Django 4.1.5 on 2024-06-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_position_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="House",
            field=models.CharField(default="X", max_length=254, null=True),
        ),
    ]
