# Generated by Django 4.1.5 on 2024-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_alter_position_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="house",
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
